apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # A separate name for the plugin's app definition
  name: argo-rollouts-openshift-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # This is the official Git repo for the plugin
    repoURL: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift
    # Point to the 'stable' branch
    targetRevision: stable
    # The directory in that repo containing the YAMLs to apply
    path: deploy 

  destination:
    server: 'https://kubernetes.default.svc'
    # Install the plugin into the SAME namespace as the controller
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true